15 implementar nivel de dificultad a usuarios
ThisIsLexx/EUV pull request #20
Opened 2024-09-29 00:51 UTC by osvaiglez

Creo que ya quedó, si puedes checarla estaría de lujo, gracias.

2024-09-30 03:08 UTC, ThisIsLexx requested changes
public function down()
{
    Schema::table('users', function($table) {
        $table->dropColumn('paid');
    });
}
Puedes implementar una función así para poder eliminar la columna?

2024-09-30 03:33 UTC, osvaiglez commented
> public function down() { Schema::table('users', function($table) { $table->dropColumn('paid'); }); } Puedes implementar una función así para poder eliminar la columna?

@ThisIsLexx, esa función va en add_dificultad_column_to_users.php?

2024-10-01 00:26 UTC, ThisIsLexx commented
@osvaiglez Si we, es para cuando se revierten las migraciones la columna sea eliminada

2024-10-01 02:33 UTC, osvaiglez commented
Según yo, ya quedó, utilicé esta doc: https://laravel.com/docs/10.x/migrations#dropping-columns

2024-10-02 06:53 UTC, ThisIsLexx approved these changes

2024-10-03 01:57 UTC, merged